name: MessageServer
description: A simple REST-based message-store server
dependencies:
  args: any
  mailer: any
  openreception_framework:
    git: https://github.com/AdaHeads/OpenReceptionFramework.git
  path: any
  postgresql: any
  route: any
  xml: 1.0.0
