name: server
description: A sample command-line application
dependencies:
  args: any
  http: any
  libdialplan:
    git:
      ref: master
      url: https://github.com/AdaHeads/libdialplan.git
  openreception_framework:
    git:
      ref: master
      url: https://github.com/AdaHeads/OpenReceptionFramework.git
  path: any
  postgresql: any
  route: any
