name: LogServer
description: A sample command-line application
dependencies:
  args: any
  intl: any
  openreception_framework:
    git:
      ref: converging_model
      url: https://github.com/AdaHeads/OpenReceptionFramework.git
  path: any
  postgresql: any
  route: any
